import {
  CSS,
  Express,
  HTML,
  JavaScript,
  Mongodb,
  Mongoose,
  Render,
  Postman,
  Krita,
  Three,
  Fusion,
  Nextjs2,
  NodeJS,
  ReactJS,
  Redux,
  Bootstrap,
  Chai,
  ChartJS,
  CSSModules,
  Cypress,
  Datefns,
  Figma,
  Git,
  Jest,
  jQuery,
  Leaflet,
  Mocha,
  Linux,
  Photoshop,
  PostgreSQL,
  ReactHookForm,
  ReactHotToast,
  ReactIcon,
  ReactQuery,
  ReactRouter,
  Recharts,
  RSpec,
  Ruby,
  SASS,
  StyledComponents,
  SQL,
  Sublime,
  Tailwind,
  Vite,
  VS,
  Axios,
  jungle,
  jungleVideo,
  photolab,
  photoVideo,
  oasisbackside,
  obsvideo,
  poll,
  pollvideo,
  blogener,
  blogenerVideo,
  pizzolino,
  pizzolinoVideo,
  mapmarker,
  mapmarkervideo,
  flashbackup,
  fbuVideo,
  Supabase,
  Auth,
  OpenAI,
} from "./assets";

export const projectStats = [
  {
    name: "Total Projects",
    value: "200+",
  },
  {
    name: "Website Design",
    value: "150+",
  },
  {
    name: "Mobile App Design",
    value: "50",
  },
  {
    name: "Clients worldwide",
    value: "+86",
  },
];

export const skills = [
  {
    name: "React",
    icon: ReactJS,
    category: "frontend",
    url: "https://reactjs.org/",
  },
  {
    name: "JavaScript",
    icon: JavaScript,
    category: "language",
    url: "https://www.javascript.com/",
  },
  {
    name: "HTML",
    icon: HTML,
    category: "language",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    name: "CSS",
    icon: CSS,
    category: "language",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    name: "NodeJS",
    icon: NodeJS,
    category: "backend",
    url: "https://nodejs.org/en",
  },
  {
    name: "Express",
    icon: Express,
    category: "backend",
    url: "https://expressjs.com/",
  },
  {
    name: "Postgresql",
    icon: PostgreSQL,
    category: "backend",
    url: "https://www.postgresql.org/",
  },
  {
    name: "React Router",
    icon: ReactRouter,
    category: "frontend",
    url: "https://reactrouter.com/en/main",
  },
  {
    name: "Redux",
    icon: Redux,
    category: "frontend",
    url: "https://redux.js.org/",
  },
  {
    name: "Axios",
    icon: Axios,
    category: "frontend",
    url: "https://axios-http.com/docs/intro",
  },
  {
    name: "React Query",
    icon: ReactQuery,
    category: "frontend",
    url: "https://tanstack.com/query/latest",
  },
  {
    name: "MongoDB",
    icon: Mongodb,
    category: "backend",
    url: "https://www.mongodb.com/",
  },
  {
    name: "Mongoose",
    icon: Mongoose,
    category: "backend",
    url: "https://www.mongoose.com/",
  },
  {
    name: "jQuery",
    icon: jQuery,
    category: "frontend",
    url: "https://jquery.com/",
  },
  {
    name: "Bootstrap",
    icon: Bootstrap,
    category: "frontend",
    url: "https://getbootstrap.com/",
  },
  {
    name: "Tailwind",
    icon: Tailwind,
    category: "frontend",
    url: "https://tailwindui.com/",
  },
  {
    name: "Chai",
    icon: Chai,
    category: "testing",
    url: "https://www.chaijs.com/",
  },
  {
    name: "OpenAI",
    icon: OpenAI,
    category: "library",
    url: "https://openai.com/",
  },
  {
    name: "Auth0",
    icon: Auth,
    category: "library",
    url: "https://auth0.com/",
  },
  {
    name: "ChartJS",
    icon: ChartJS,
    category: "library",
    url: "https://www.chartjs.org/docs/latest/",
  },
  {
    name: "Cypress",
    icon: Cypress,
    category: "testing",
    url: "https://www.cypress.io/",
  },
  {
    name: "date-fns",
    icon: Datefns,
    category: "library",
    url: "https://date-fns.org/",
  },
  {
    name: "Figma",
    icon: Figma,
    category: "design",
    url: "https://www.figma.com/",
  },
  {
    name: "Git",
    icon: Git,
    category: "tool",
    url: "",
  },
  {
    name: "Jest",
    icon: Jest,
    category: "testing",
    url: "",
  },
  {
    name: "React Leaflet",
    icon: Leaflet,
    category: "library",
    url: "https://react-leaflet.js.org/",
  },
  {
    name: "Mocha",
    icon: Mocha,
    category: "testing",
    url: "https://mochajs.org/",
  },
  {
    name: "Photoshop",
    icon: Photoshop,
    category: "design",
    url: "",
  },
  {
    name: "React Hook Form",
    icon: ReactHookForm,
    category: "library",
    url: "https://react-hook-form.com/",
  },
  {
    name: "React Hot Toast",
    icon: ReactHotToast,
    category: "library",
    url: "https://react-hot-toast.com/",
  },
  {
    name: "React Icon",
    icon: ReactIcon,
    category: "library",
    url: "https://react-icons.github.io/react-icons",
  },

  {
    name: "Recharts",
    icon: Recharts,
    category: "library",
    url: "https://recharts.org/en-US/",
  },
  {
    name: "RSpec",
    icon: RSpec,
    category: "testing",
    url: "https://rspec.info/",
  },
  {
    name: "Ruby",
    icon: Ruby,
    category: "language",
    url: "https://rubyonrails.org/",
  },
  {
    name: "SASS",
    icon: SASS,
    category: "frontend",
    url: "https://sass-lang.com/",
  },
  {
    name: "Styled Components",
    icon: StyledComponents,
    category: "frontend",
    url: "https://styled-components.com/",
  },
  {
    name: "CSS Modules",
    icon: CSSModules,
    category: "frontend",
    url: "https://github.com/css-modules/css-modules",
  },
  {
    name: "Vite",
    icon: Vite,
    category: "tool",
    url: "https://vitejs.dev/",
  },
  {
    name: "Visual Studio",
    icon: VS,
    category: "tool",
    url: "https://code.visualstudio.com/",
  },
  {
    name: "SQL",
    icon: SQL,
    category: "language",
    url: "https://developer.mozilla.org/en-US/docs/Glossary/SQL",
  },
  {
    name: "Supabase",
    icon: Supabase,
    category: "backend",
    url: "https://supabase.com/",
  },
  {
    name: "Sublime",
    icon: Sublime,
    category: "tool",
    url: "https://www.sublimetext.com/",
  },
  {
    name: "Linux",
    icon: Linux,
    category: "tool",
    url: "",
  },
  {
    name: "FusionCharts",
    icon: Fusion,
    category: "library",
    url: "https://www.fusioncharts.com/",
  },
  {
    name: "Postman",
    icon: Postman,
    category: "tool",
    url: "https://www.postman.com/",
  },
  {
    name: "Render",
    icon: Render,
    category: "tool",
    url: "https://www.render.com/",
  },
  {
    name: "Krita",
    icon: Krita,
    category: "design",
    url: "https://krita.org/en/",
  },
  {
    name: "Three.js",
    icon: Three,
    category: "library",
    url: "https://threejs.org/",
  },
  {
    name: "NextJS",
    icon: Nextjs2,
    category: "frontend",
    url: "https://nextjs.org/",
  },
];

export const projects = [
  {
    id: 1,
    title: "Oasis Backside",
    description:
      "Oasis Backside is the internal application used inside the hotel to manage bookings, rooms, and guests. New users can only be signed up inside the application. Users can create, update and delete hotel rooms. Users can delete, check in, or check out a booking.",
    technologies: [
      "React",
      "React Router",
      "React Query",
      "React Hook Forms",
      "Supabase",
      "Styled Components",
    ],
    url: "https://oasis-backside.netlify.app/",
    git: "https://github.com/agpavlik/Oasis-Backside",
    img: oasisbackside,
    video: obsvideo,
  },
  {
    id: 2,
    title: "Blogener",
    description:
      "The AI-powered SAAS solution to generate SEO-optimized blog posts in minutes. Get high-quality content, without sacrificing your time.",
    technologies: [
      "OpenAI",
      "React.js",
      "Next.js",
      "Tailwind",
      "MongoDB",
      "Auth0",
      "Stripe",
      "FontAwesome",
    ],
    url: "https://hammerhead-app-p5fmi.ondigitalocean.app/",
    git: "https://github.com/agpavlik/Blogener",
    img: blogener,
    video: blogenerVideo,
  },
  {
    id: 3,
    title: "Flashback-Up",
    description:
      "A React-based SPA that allows users to store remarkable places that they would like to memorize and share with the community.",
    technologies: [
      "React",
      "React Router",
      "Axios",
      "Node",
      "Express",
      "MongoDB",
      "Mongoose",
      "bcrypt.js",
      "jsonwebtoken",
    ],
    url: "https://flashback-up.netlify.app/",
    git: "https://github.com/agpavlik/Geo",
    img: flashbackup,
    video: fbuVideo,
  },
  {
    id: 4,
    title: "Pizzolino",
    description:
      "The application allows users to order pizza fast requiring no user account and no login. User can add multiple pizzas to a card and mark order 'priority'. Also User can provide a GPS location to make delivery easier",
    technologies: ["React", "React Router", "Redux", "Tailwind CSS"],
    url: "https://pizzolino.netlify.app/",
    git: "https://github.com/agpavlik/Pizzolino",
    img: pizzolino,
    vide0: pizzolinoVideo,
  },
  {
    id: 5,
    title: "Map-Marker",
    description:
      "Single-page application where users can register all the cities that they have ever traveled to. User can explore the world through an intuitive map interface, fetch and store the city by click. Each city has details, including its name, country, and additional notes user wants to attach. User also can delete cities from the list.",
    technologies: ["React", "React Router", "CSS Modules", "React Leaflet"],
    url: "https://maps-marker.netlify.app/",
    git: "https://github.com/agpavlik/Map-Marker",
    img: mapmarker,
    video: mapmarkervideo,
  },
  {
    id: 6,
    title: "PhotoLabs",
    description:
      "A React-based SPA that allows users to view photos in different contexts. User can navigate to different photo categories and mark photos. User can click on a photo to view of its larger version.",
    technologies: ["React", "Bootstrap", "Node", "Express", "MongoDB"],
    git: "https://github.com/agpavlik/LHL-project-photolabs",
    img: photolab,
    video: photoVideo,
  },
  {
    id: 7,
    title: "Pollarazing",
    description:
      "App allows users to make a decision by creating polls. A creator can add dozens of answer options and comments. The poll is shared through emails. The voting process was realized with drag-and-drop functionality. Result is shown on the bar chart.",
    technologies: [
      "JavaScript",
      "HTML",
      "SASS",
      "Bootstrap",
      "Chart.js",
      "Node",
      "Express",
      "PostgreSQL",
    ],
    git: "https://github.com/agpavlik/LHL-project-decision-maker",
    img: poll,
    video: pollvideo,
  },

  {
    id: 8,
    title: "Jungle",
    description:
      "Plants and flowers online shop. Authentication functionality. User can observe various categories of products, fill the basket in, and buy chosen products using the card. The admin can provide some manipulation by adding/deleting products and categories.",
    technologies: ["Ruby on Rails", "PostgreSQL", "Strap"],
    git: "https://github.com/agpavlik/LHL-project-Jungle",
    img: jungle,
    video: jungleVideo,
  },
];

export const softskills = [
  "Time management",
  "Communication",
  "Empathy",
  "Teamwork",
  "Helpfulness",
  "Creativity",
  "Self-learning",
  "Accountability",
  "Problem solving",
  "Open-mindedness",
];
