import {
  CSS,
  Express,
  HTML,
  JavaScript,
  Mongodb,
  Nextjs,
  Nextjs2,
  NodeJS,
  ReactJS,
  Redux,
  Bootstrap,
  Chai,
  ChartJS,
  CSSModules,
  Cypress,
  Datefns,
  Figma,
  Git,
  Jest,
  jQuery,
  Leaflet,
  Mocha,
  Linux,
  Photoshop,
  PostgreSQL,
  Rails,
  ReactHookForm,
  ReactHotToast,
  ReactIcon,
  ReactQuery,
  ReactRouter,
  Recharts,
  RSpec,
  Ruby,
  SASS,
  StyledComponents,
  SQL,
  Sublime,
  Tailwind,
  Vite,
  VS,
  admin,
  food,
  food1,
  port1,
  port2,
  port3,
  social,
  demo9,
  Supabase,
} from "./assets";

export const projectStats = [
  {
    name: "Total Projects",
    value: "200+",
  },
  {
    name: "Website Design",
    value: "150+",
  },
  {
    name: "Mobile App Design",
    value: "50",
  },
  {
    name: "Clients worldwide",
    value: "+86",
  },
];

export const tools = [
  {
    name: "MongoDB",
    icon: Mongodb,
  },
  {
    name: "Express",
    icon: Express,
  },
  {
    name: "React",
    icon: ReactJS,
  },
  {
    name: "NodeJS",
    icon: NodeJS,
  },
  {
    name: "NextJS",
    icon: Nextjs2,
  },
];

export const skills = [
  {
    name: "React",
    icon: ReactJS,
    category: "framework",
  },
  {
    name: "JavaScript",
    icon: JavaScript,
    category: "language",
  },
  {
    name: "HTML",
    icon: HTML,
    category: "language",
  },
  {
    name: "CSS",
    icon: CSS,
    category: "language",
  },
  {
    name: "Postgresql",
    icon: PostgreSQL,
    category: "database",
  },
  {
    name: "React Router",
    icon: ReactRouter,
    category: "framework",
  },
  {
    name: "Redux",
    icon: Redux,
    category: "framework",
  },
  {
    name: "NextJS",
    icon: Nextjs2,
    category: "framework",
  },
  {
    name: "MongoDB",
    icon: Mongodb,
    category: "database",
  },
  {
    name: "NodeJS",
    icon: NodeJS,
    category: "framework",
  },
  {
    name: "Express",
    icon: Express,
    category: "framework",
  },

  {
    name: "Bootstrap",
    icon: Bootstrap,
    category: "framework",
  },
  {
    name: "Chai",
    icon: Chai,
    category: "testing",
  },
  {
    name: "CSS Modules",
    icon: CSSModules,
    category: "framework",
  },
  {
    name: "ChartJS",
    icon: ChartJS,
    category: "framework",
  },
  {
    name: "Cypress",
    icon: Cypress,
    category: "testing",
  },
  {
    name: "date-fns",
    icon: Datefns,
    category: "framework",
  },
  {
    name: "Figma",
    icon: Figma,
    category: "design",
  },
  {
    name: "Git",
    icon: Git,
    category: "tools",
  },
  {
    name: "Jest",
    icon: Jest,
    category: "testing",
  },
  {
    name: "jQuery",
    icon: jQuery,
    category: "framework",
  },
  {
    name: "Leaflet",
    icon: Leaflet,
    category: "framework",
  },
  {
    name: "Mocha",
    icon: Mocha,
    category: "testing",
  },
  {
    name: "Photoshop",
    icon: Photoshop,
    category: "design",
  },
  {
    name: "Rails",
    icon: Rails,
    category: "framework",
  },
  {
    name: "React Hook Form",
    icon: ReactHookForm,
    category: "framework",
  },
  {
    name: "React Hot Toast",
    icon: ReactHotToast,
    category: "framework",
  },
  {
    name: "React Icon",
    icon: ReactIcon,
    category: "framework",
  },
  {
    name: "React Query",
    icon: ReactQuery,
    category: "framework",
  },
  {
    name: "Recharts",
    icon: Recharts,
    category: "framework",
  },
  {
    name: "RSpec",
    icon: RSpec,
    category: "testing",
  },
  {
    name: "Ruby",
    icon: Ruby,
    category: "language",
  },
  {
    name: "SASS",
    icon: SASS,
    category: "framework",
  },
  {
    name: "Styled Components",
    icon: StyledComponents,
    category: "framework",
  },
  {
    name: "Tailwind",
    icon: Tailwind,
    category: "framework",
  },
  {
    name: "Vite",
    icon: Vite,
    category: "tools",
  },
  {
    name: "VS",
    icon: VS,
    category: "framework",
  },
  {
    name: "SQL",
    icon: SQL,
    category: "language",
  },
  {
    name: "Supabase",
    icon: Supabase,
    category: "database",
  },
  {
    name: "Linux",
    icon: Linux,
    category: "tools",
  },
];

export const projects = [
  {
    id: 1,
    title: "Admin Dashboard",
    cat: "Web Design",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: admin,
    video: demo9,
  },
  {
    id: 2,
    title: "Portfolio Website",
    cat: "Web Design",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: port1,
    vide0: 2,
  },
  {
    id: 3,
    title: "Portfolio Website",
    cat: "Web Design",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: port2,
    video: 3,
  },
  {
    id: 4,
    title: "MTS Website",
    cat: "Web Design",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: port3,
    video: 4,
  },
  {
    id: 5,
    title: "Eat Well Website",
    cat: "Web Design",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: food,
    video: 5,
  },
  {
    id: 6,
    title: "Social Media",
    cat: "Web App",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: social,
    video: 6,
  },
  {
    id: 7,
    title: "Eat Well App",
    cat: "Mobile App",
    description: "lorem",
    technologies: ["React", "CSS"],
    url: "",
    git: "",
    img: food1,
    video: 7,
  },
];

export const softskills = [
  "Time management",
  "Communication",
  "Empathy",
  "Teamwork",
  "Helpfulness",
  "Creativity",
  "Self-learning",
  "Accountability",
  "Problem solving",
  "Open-mindedness",
];
